import { execFile } from "node:child_process";
import { access, readFile, stat } from "node:fs/promises";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

export const DEFAULT_SLICING_TIMEOUT_MS = 120_000;
const MIN_GCODE_BYTES = 1024;

const MATERIAL_TEMPERATURES = {
  pla: {
    nozzle: 200,
    bed: 60,
  },
  "pla-plus": {
    nozzle: 210,
    bed: 60,
  },
  petg: {
    nozzle: 235,
    bed: 75,
  },
};

export class SlicingError extends Error {
  constructor(code, message, cause) {
    super(message, { cause });
    this.name = "SlicingError";
    this.code = code;
    this.statusCode = 422;
  }
}

async function executePrusaSlicer(args, timeoutMs) {
  return execFileAsync(
    "xvfb-run",
    [
      "--auto-servernum",
      "--server-args=-screen 0 1024x768x24",
      "prusa-slicer",
      ...args,
    ],
    {
      timeout: timeoutMs,
      maxBuffer: 10 * 1024 * 1024,
    },
  );
}

function buildSlicerArgs({
  inputPath,
  outputPath,
  profilePath,
  settings,
}) {
  const temperatures = MATERIAL_TEMPERATURES[settings.material];

  if (!temperatures) {
    throw new SlicingError(
      "SLICING_FAILED",
      "No existe una configuración de temperatura para el material.",
    );
  }

  return [
    "--load",
    profilePath,
    "--layer-height",
    String(settings.layerHeightMm),
    "--fill-density",
    `${settings.infillPercent}%`,
    settings.supports
      ? "--support-material"
      : "--no-support-material",
    "--temperature",
    String(temperatures.nozzle),
    "--first-layer-temperature",
    String(temperatures.nozzle),
    "--bed-temperature",
    String(temperatures.bed),
    "--first-layer-bed-temperature",
    String(temperatures.bed),
    "--export-gcode",
    "--output",
    outputPath,
    inputPath,
  ];
}

async function validateGcodeFile(outputPath) {
  await access(outputPath);

  const fileStats = await stat(outputPath);

  if (!fileStats.isFile() || fileStats.size < MIN_GCODE_BYTES) {
    throw new SlicingError(
      "SLICING_FAILED",
      "PrusaSlicer generó un archivo G-code vacío o incompleto.",
    );
  }

  const gcode = await readFile(outputPath, "utf8");

  const hasGeneratorHeader = gcode.includes(
    "; generated by PrusaSlicer",
  );

  const hasMovement = /^G[01][ \t]/m.test(gcode);
  const hasExtrusion = /^G1.*[ \t]E[-+]?[0-9]/m.test(gcode);

  if (!hasGeneratorHeader || !hasMovement || !hasExtrusion) {
    throw new SlicingError(
      "SLICING_FAILED",
      "El archivo generado no contiene G-code válido.",
    );
  }

  return {
    outputPath,
    sizeBytes: fileStats.size,
  };
}

export async function runPrusaSlicer({
  inputPath,
  outputPath,
  profilePath,
  settings,
  timeoutMs = DEFAULT_SLICING_TIMEOUT_MS,
  execute = executePrusaSlicer,
}) {
  if (!inputPath || !outputPath || !profilePath || !settings) {
    throw new SlicingError(
      "SLICING_FAILED",
      "Faltan datos necesarios para ejecutar el laminador.",
    );
  }

  const args = buildSlicerArgs({
    inputPath,
    outputPath,
    profilePath,
    settings,
  });

  try {
    await execute(args, timeoutMs);
    return await validateGcodeFile(outputPath);
  } catch (error) {
    if (error instanceof SlicingError) {
      throw error;
    }

    const timedOut =
      error?.code === "ETIMEDOUT" ||
      error?.killed === true ||
      error?.signal === "SIGTERM";

    throw new SlicingError(
      "SLICING_FAILED",
      timedOut
        ? "PrusaSlicer superó el tiempo máximo de 120 segundos."
        : "PrusaSlicer no pudo generar el archivo G-code.",
      error,
    );
  }
}
