import assert from "node:assert/strict";
import { once } from "node:events";
import { test } from "node:test";

import { SlicingError } from "../src/prusa-runner.mjs";
import { createSlicerServer } from "../src/server.mjs";

async function startTestServer({
  sliceModel = async () => ({
    gcode: Buffer.from(
      "; generated by PrusaSlicer\nG28\nG1 X10 Y10 E1\n",
    ),
    fileName: "pieza.gcode",
    sizeBytes: 49,
  }),
} = {}) {
  const server = createSlicerServer({
    resolveSlicerVersion: async () => "PrusaSlicer-2.9.2",
    sliceModel,
  });

  server.listen(0, "127.0.0.1");
  await once(server, "listening");

  const address = server.address();

  if (!address || typeof address === "string") {
    throw new Error("No se pudo obtener el puerto del servidor.");
  }

  return {
    server,
    baseUrl: `http://127.0.0.1:${address.port}`,
  };
}

function createValidFormData() {
  const formData = new FormData();

  formData.set(
    "file",
    new File(["solid test"], "pieza.stl", {
      type: "model/stl",
    }),
  );

  formData.set("printerProfileId", "biqu-b1-0.4");
  formData.set("layerHeightMm", "0.2");
  formData.set("infillPercent", "20");
  formData.set("supports", "false");
  formData.set("material", "pla");

  return formData;
}

test("POST /v1/slice devuelve G-code descargable", async (t) => {
  let receivedRequest;

  const { server, baseUrl } = await startTestServer({
    sliceModel: async (request) => {
      receivedRequest = request;

      return {
        gcode: Buffer.from(
          "; generated by PrusaSlicer\nG28\nG1 X10 Y10 E1\n",
        ),
        fileName: "pieza.gcode",
        sizeBytes: 49,
      };
    },
  });

  t.after(() => server.close());

  const response = await fetch(`${baseUrl}/v1/slice`, {
    method: "POST",
    body: createValidFormData(),
  });

  const gcode = await response.text();

  assert.equal(response.status, 200);
  assert.equal(response.headers.get("content-type"), "text/x-gcode");
  assert.equal(
    response.headers.get("content-disposition"),
    'attachment; filename="pieza.gcode"',
  );

  assert.equal(
    response.headers.get("x-printer-profile-id"),
    "biqu-b1-0.4",
  );

  assert.equal(
    response.headers.get("x-layer-height-mm"),
    "0.2",
  );

  assert.equal(
    response.headers.get("x-infill-percent"),
    "20",
  );

  assert.equal(
    response.headers.get("x-supports"),
    "false",
  );

  assert.equal(
    response.headers.get("x-material"),
    "pla",
  );

  assert.match(gcode, /generated by PrusaSlicer/);
  assert.equal(receivedRequest.file.name, "pieza.stl");

  assert.deepEqual(receivedRequest.settings, {
    printerProfileId: "biqu-b1-0.4",
    layerHeightMm: 0.2,
    infillPercent: 20,
    supports: false,
    material: "pla",
  });

  assert.equal(typeof receivedRequest.requestId, "string");
});

test("POST /v1/slice rechaza solicitudes sin archivo", async (t) => {
  const { server, baseUrl } = await startTestServer();
  const formData = createValidFormData();

  t.after(() => server.close());

  formData.delete("file");

  const response = await fetch(`${baseUrl}/v1/slice`, {
    method: "POST",
    body: formData,
  });

  const body = await response.json();

  assert.equal(response.status, 400);
  assert.equal(body.error.code, "INVALID_FILE");
  assert.equal(typeof body.error.requestId, "string");
});

test("POST /v1/slice rechaza materiales inválidos", async (t) => {
  const { server, baseUrl } = await startTestServer();
  const formData = createValidFormData();

  t.after(() => server.close());

  formData.set("material", "abs");

  const response = await fetch(`${baseUrl}/v1/slice`, {
    method: "POST",
    body: formData,
  });

  const body = await response.json();

  assert.equal(response.status, 400);
  assert.equal(body.error.code, "INVALID_MATERIAL");
});

test("POST /v1/slice exige multipart/form-data", async (t) => {
  const { server, baseUrl } = await startTestServer();

  t.after(() => server.close());

  const response = await fetch(`${baseUrl}/v1/slice`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      printerProfileId: "biqu-b1-0.4",
    }),
  });

  const body = await response.json();

  assert.equal(response.status, 415);
  assert.equal(body.error.code, "UNSUPPORTED_MEDIA_TYPE");
});

test("POST /v1/slice devuelve SLICING_FAILED si falla PrusaSlicer", async (t) => {
  const { server, baseUrl } = await startTestServer({
    sliceModel: async () => {
      throw new SlicingError(
        "SLICING_FAILED",
        "PrusaSlicer no pudo generar el archivo G-code.",
      );
    },
  });

  t.after(() => server.close());

  const response = await fetch(`${baseUrl}/v1/slice`, {
    method: "POST",
    body: createValidFormData(),
  });

  const body = await response.json();

  assert.equal(response.status, 422);
  assert.equal(body.error.code, "SLICING_FAILED");
  assert.equal(typeof body.error.requestId, "string");
});

test("GET /v1/slice devuelve 405", async (t) => {
  const { server, baseUrl } = await startTestServer();

  t.after(() => server.close());

  const response = await fetch(`${baseUrl}/v1/slice`);
  const body = await response.json();

  assert.equal(response.status, 405);
  assert.equal(response.headers.get("allow"), "POST");
  assert.equal(body.error, "Método no permitido.");
});
