import assert from "node:assert/strict";
import { access, writeFile } from "node:fs/promises";
import { test } from "node:test";

import { sliceUploadedModel } from "../src/slice-service.mjs";

function createTestFile(name = "pieza útil.stl") {
  return new File(["solid test"], name, {
    type: "model/stl",
  });
}

const settings = {
  printerProfileId: "biqu-b1-0.4",
  layerHeightMm: 0.2,
  infillPercent: 20,
  supports: false,
  material: "pla",
};

test("guarda el STL, ejecuta el runner y devuelve el G-code", async () => {
  let receivedInputPath;
  let receivedOutputPath;
  let receivedProfilePath;
  let receivedSettings;

  const result = await sliceUploadedModel({
    file: createTestFile(),
    settings,
    requestId: "request-prueba",
    profilePath: "/profiles/biqu-b1.ini",
    runSlicer: async ({
      inputPath,
      outputPath,
      profilePath,
      settings: runnerSettings,
    }) => {
      receivedInputPath = inputPath;
      receivedOutputPath = outputPath;
      receivedProfilePath = profilePath;
      receivedSettings = runnerSettings;

      await access(inputPath);

      const gcode = Buffer.from(
        "; generated by PrusaSlicer\nG28\nG1 X10 Y10 E1\n",
      );

      await writeFile(outputPath, gcode);

      return {
        outputPath,
        sizeBytes: gcode.length,
      };
    },
  });

  assert.match(receivedInputPath, /pieza-util\.stl$/);
  assert.match(receivedOutputPath, /pieza-util\.gcode$/);
  assert.equal(receivedProfilePath, "/profiles/biqu-b1.ini");
  assert.deepEqual(receivedSettings, settings);

  assert.equal(result.fileName, "pieza-util.gcode");
  assert.match(result.gcode.toString(), /generated by PrusaSlicer/);
});

test("limpia la carpeta temporal aunque el runner falle", async () => {
  let inputPath;

  await assert.rejects(
    sliceUploadedModel({
      file: createTestFile("fallo.stl"),
      settings,
      requestId: "request-fallida",
      runSlicer: async ({ inputPath: receivedInputPath }) => {
        inputPath = receivedInputPath;
        throw new Error("falló el laminado");
      },
    }),
    /falló el laminado/,
  );

  await assert.rejects(access(inputPath));
});

test("usa un nombre seguro para el archivo de salida", async () => {
  const result = await sliceUploadedModel({
    file: createTestFile("../../pieza rara ñ.stl"),
    settings,
    requestId: "request-nombre",
    runSlicer: async ({ outputPath }) => {
      const gcode = Buffer.from(
        "; generated by PrusaSlicer\nG28\nG1 X1 Y1 E1\n",
      );

      await writeFile(outputPath, gcode);

      return {
        outputPath,
        sizeBytes: gcode.length,
      };
    },
  });

  assert.equal(result.fileName, "pieza-rara-n.gcode");
  assert.equal(result.fileName.includes(".."), false);
  assert.equal(result.fileName.includes("/"), false);
});
